-- liquibase formatted sql

--changeset leushkin:1
CREATE TABLE if not exists notification_task
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT          NOT NULL,
    message_content TEXT    NOT NULL,
    time_stamp TIMESTAMP    NOT NULL,
    sent_message BOOLEAN    NOT NULL DEFAULT FALSE
);
